2018-10-12 12:34:23,326 ERROR: Exception on /index [GET] [in c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Konstantin\projects\microblog\myapp\routes.py", line 39, in index
    return render_template('index.html', title='Home page', posts=posts)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\index.html", line 1, in top-level template code
    {% extends "base.html"%}
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-10-12 12:34:28,131 ERROR: Exception on /index [GET] [in c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Konstantin\projects\microblog\myapp\routes.py", line 39, in index
    return render_template('index.html', title='Home page', posts=posts)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\index.html", line 1, in top-level template code
    {% extends "base.html"%}
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-10-12 12:34:31,766 ERROR: Exception on /index [GET] [in c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Konstantin\projects\microblog\myapp\routes.py", line 39, in index
    return render_template('index.html', title='Home page', posts=posts)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\index.html", line 1, in top-level template code
    {% extends "base.html"%}
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Konstantin\projects\microblog\myapp\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\konstantin\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-10-12 12:35:31,795 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 12:46:48,320 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 12:47:05,511 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 12:47:44,574 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 13:11:25,386 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 13:17:36,808 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 13:18:03,297 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 13:36:26,706 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 13:51:02,877 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
2018-10-12 14:35:40,058 INFO: Microblog startup [in C:\Users\Konstantin\projects\microblog\myapp\__init__.py:45]
